console.log("Starting with Javascript")
console.log(36+1)
document.write("<h3 style=\"color: red\">Incorporated text by JS</h3>")
console.info(5)
console.warn("Warning text")
console.error("Error text")
document.write("Hi!")